constexpr char const * compute_shader_yuv_444_8 =
{
"#version 430\n"
"\n"
"layout(local_size_x = 8, local_size_y = 8) in;\n"
"\n"
"layout(rgba8, binding = 0) uniform image2D img_output;\n"
"layout(rgba8, binding = 1) uniform image2D img_input;\n"
"\n"
"vec4 yuv2rgba(vec4 yuvk)\n"
"{\n"
"    vec4 rgba;\n"
"    bool bt_709 = true; //TODO: pass this information from the code\n"
"\n"
"    rgba.x = 1.164 * (yuvk.x - 16.0 / 255.0) + ((float(bt_709) * 1.793) + (float(!bt_709)) * (1.596)) * (yuvk.z - 128.0 / 255.0);\n"
"    rgba.y = 1.164 * (yuvk.x - 16.0 / 255.0) - ((float(bt_709) * 0.534) + (float(!bt_709)) * (0.813)) * (yuvk.z - 128.0 / 255.0) - 0.213 * (yuvk.y - 128.0 / 255.0);\n"
"    rgba.z = 1.164 * (yuvk.x - 16.0 / 255.0) + ((float(bt_709) * 2.115) + (float(!bt_709)) * (2.018)) * (yuvk.y - 128.0 / 255.0);\n"
"    rgba.w = 1.0;\n"
"    return rgba;\n"
"}\n"
"\n"
"void main() {\n"
"    int width = imageSize(img_output).x;\n"
"    ivec2 coords = ivec2(gl_GlobalInvocationID);\n"
"    float PxlIdx = coords.x + coords.y * width;\n"
"    vec4 uyvk;\n"
"    vec4 yuvk;\n"
"    yuvk.w = 1.0;\n"
"    if (mod(PxlIdx, 4.0) < 1.0)\n"
"    {\n"
"       uyvk = imageLoad(img_input, ivec2(coords.x*3.0/4.0 , coords.y));\n"
"       yuvk.y = uyvk.x;\n"
"       yuvk.x = uyvk.y;\n"
"       yuvk.z = uyvk.z;\n"
"    }\n"
"    else if (mod(PxlIdx, 4.0) < 2.0)\n"
"    {\n"
"       uyvk = imageLoad(img_input, ivec2(int(coords.x*3.0/4.0)  , coords.y));\n"
"       yuvk.y = uyvk.w;\n"
"       uyvk = imageLoad(img_input, ivec2(int(coords.x*3.0/4.0) + 1 , coords.y));\n"
"       yuvk.x = uyvk.x;\n"
"       yuvk.z = uyvk.y;\n"
"    }\n"
"    else if (mod(PxlIdx, 4.0) < 3.0)\n"
"    {\n"
"       uyvk = imageLoad(img_input, ivec2(int(coords.x*3.0/4.0) , coords.y));\n"
"       yuvk.y = uyvk.z;\n"
"       yuvk.x = uyvk.w;\n"
"       uyvk = imageLoad(img_input, ivec2(int(coords.x*3.0/4.0) + 1 , coords.y));\n"
"       yuvk.z = uyvk.x;\n"
"    }\n"
"    else if (mod(PxlIdx, 4.0) < 4.0)\n"
"    {\n"
"       uyvk = imageLoad(img_input, ivec2(int(coords.x*3.0/4.0) , coords.y));\n"
"       yuvk.y = uyvk.y;\n"
"       yuvk.x = uyvk.z;\n"
"       yuvk.z = uyvk.w;\n"
"    }\n"
"\n"
"    vec4 pixel = yuv2rgba(yuvk);\n"
"\n"
"    imageStore(img_output, coords, pixel);\n"
"}\n"
}; 